### ISSUE TITLE
Will this control multiple units independently?

### ISSUE THREAD

**Issue by iandouglas** [zource-dev/litra-glow#3]
I have four Litra Glow units and it irritates me beyond words that setting up G Hub software controls all of them exactly the same. If I turn one light on, they ALL come on, when I set the color temp on one it sets ALL of them.

Will this software allow me to set each one independently?

**Comment by 3axap4eHko** [comment]
I've never tested it on multiple devices, but the software is designed to interact with a single device

**Comment by iandouglas** [comment]
Logitech has since allowed their G Hub software to set each light independently.
